### PR TITLE
Advanced: Making Dynamic Decisions and the Bi-LSTM CRF 校对

### PR DESCRIPTION
**Pull request by enningxie**
Advanced: Making Dynamic Decisions and the Bi-LSTM CRF 校对

### CODE REVIEW

**Comment by wizardforcel** [comment]
请拉去最新提交然后修复冲突。

**Comment by jiangzhonglian** [comment]
我来处理！别动哈

**Comment by jiangzhonglian** [comment]
@enningxie  你再重新拉去一下最新代码，然后提交一下，我们再看看diff

**Comment by enningxie** [comment]
ok

**Pull request closed without merging**
